### ISSUE TITLE
Implement the protected route functionality in client side

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#437]
**Present scenario:**
As of now, there is no protected route, so the unregistered user can also access all the components by simply navigating to the route

**Expected outcome**
Only the registered users will be able to access the restricted components.

**UI changes**
No UI changes required

**Additional context:**
**Working on it**

**Comment by tanujvyas10** [comment]
@Rupeshiya hey, i know protected route is needed but should we add this feature later in development session because you this in the upcoming development time , the contributors will have to do many testing while working on any issue , so repeating login and token expiring is kind of annoying some time .
Its my suggestion ,we shall add the protected routes later

**Comment by Rupeshiya** [comment]
@tanujvyas10 I know that.
But as we are maintaining state so no need to do any verification as of now, I will set that to default true now, so there will not be an issue in testing.
